name: 'rust-cargo'
description: 'Run cargo command'
author: 'actions-rs team'
branding:
  icon: play-circle
  color: black
inputs:
  command:
    description: Cargo command to run (ex. `check` or `build`)
    required: true
  toolchain:
    description: Toolchain to use (without the `+` sign, ex. `nightly`)
    required: false
  args:
    description: Arguments for the cargo command
    required: false
  use-cross:
    description: Use cross instead of cargo
    default: false
outputs:
  stdout:
    description: Standard out of the program
  stderr:
    description: Standard err of the program

runs:
  using: 'node12'
  main: 'dist/index.js'
