name: "rust-cargo"
description: "Run cargo command"
author: "ructions team"
branding:
  icon: play-circle
  color: "gray-dark"
inputs:
  command:
    description: Cargo command to run (ex. `check` or `build`)
    required: true
  toolchain:
    description: Toolchain to use (without the `+` sign, ex. `nightly`)
    default: stable
    required: false
  args:
    description: Arguments for the cargo command
    required: false
  use_cross:
    description: Use cross instead of cargo
    default: "false"
    required: false

runs:
  using: "node16"
  main: "dist/index.js"
